View
SimonGrchevski/MeaningfulName pull request #6
Opened 2021-11-03 21:30 UTC by SimonGrchevski

- Created routes and view
   - /users
   - /users/show
   - /users/:id/post
   - /users/:id/post/:id
- Add stylezzzzzz

2021-11-03 22:12 UTC, DeliceLydia requested changes
## Hi @SimonGrchevski, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Required Changes ♻️
_Check the comments under the review._



### Cheers and Happy coding!👏👏👏

Feel free to leave a question, or a comment on the PR thread if something is not clear 100%. 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-03 22:12 UTC, DeliceLydia commented on app/controllers/users_controller.rb
>  end
- [ ] Remember you need to have a recent_post method that will display only 3recent posts of the user
and when a person wants to view all the user posts will hit `show all posts` link

2021-11-03 22:12 UTC, DeliceLydia commented on app/views/posts/show.html.erb
> +  </section>
- [ ] When showing a post you should have only 5recent comments but currently you are rendering all comments please work on that

2021-11-04 17:35 UTC, emmanuellekamwa approved these changes
**STATUS: APPROVED ✔🎉**
Hello @SimonGrchevski 👋🏽
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-04 18:32 UTC, merged